controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: 2.361.2-lts-jdk17
  resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "2000m"
    memory: "4096Mi"
  serviceType: LoadBalancer
  servicePort: 80
  installPlugins:
    - kubernetes:3600.v144b_cd192ca_a_
    - workflow-aggregator:581.v0c46fa_697ffd
    - git:4.11.3
    - configuration-as-code:1512.vb_79d418d5fc8
  ingress:
    enabled: false
  secondaryingress:
    enabled: false
  prometheus:
    enabled: false
  testEnabled: true

agent:
  enabled: true

#Mejorar urgente, previa configuracion de StorageClass
persistence:
  enabled: true
  storageClass:
  accessMode: "ReadWriteOnce"
  size: "8Gi"

networkPolicy:
  enabled: false

rbac:
  create: true
  readSecrets: false

serviceAccount:
  create: true

serviceAccountAgent:
  create: false

backup:
  enabled: false